[pytest]
DJANGO_SETTINGS_MODULE = todo.core.settings.development
python_files = tests.py test_*.py *_test.py
addopts = --reuse-db -n auto
markers =
    model: tests targeting the Django model layer
    api: tests targeting the DRF API endpoints
