# Generated by Django 6.0.3 on 2026-03-05 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_category_emoji'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='emoji',
            new_name='icon',
        ),
    ]
