# Generated by Django 6.0.3 on 2026-03-05 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_set_max_length_50_all_string_fields'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='description',
            new_name='title',
        ),
    ]
